### ISSUE TITLE
Windows defender marks this as a false positive

### ISSUE THREAD

**Issue by thealonealex** [neurokitti/Arc_Palette#82]
windows 10 22h2...
it doesnt even let me download it!
it says "Found: Trojan:Win32/Phonzy.A!ml"

**Comment by StudioMovieGirl** [comment]
Because we use pyinstaller windows marks it as a false positive. Try installing the program manually to avoid windows defender

**Comment by thealonealex** [comment]
I ran the installer scripts and it works! Thanks for that

**Comment by Andrew-J-Larson** [comment]
> Because we use pyinstaller windows marks it as a false positive. Try installing the program manually to avoid windows defender

We are actually using nuitka for Windows now, which produces a little less false positives, but unfortunately it seems like all the compilers for Python code will cause false positives.

**Comment by Andrew-J-Larson** [comment]
More info about this, by default, most antiviruses are going to mark *any* Python compiled executable (on Windows) as malware, since it's a common way that bad actors make malware. More specifically, they mark any compiled versions that aren't code signed.

Code signing requires having a code signing certificate, which costs money to obtain, and has to be renewed with each year, and their are no free certificates (not even for open-source apps).

So, the best thing we can do is to constantly report that to each antivirus that the EXE detection is a false positive, which just takes time and patience.
